# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.TextField()),
                ('date_posted', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('kind', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit'), ('INT', 'Interest'), ('DIV', 'Dividend'), ('FEE', 'FI Fee'), ('SRVCHG', 'Service Charge'), ('DEP', 'Deposit'), ('ATM', 'ATM'), ('POS', 'Point of Sale'), ('XFER', 'Transfer'), ('CHECK', 'Check'), ('PAYMENT', 'Electronic Payment'), ('CASH', 'Cash Withdrawal'), ('DIRECTDEP', 'Direct Deposit'), ('DIRECTDEBIT', 'Direct Debit'), ('REPEATPMT', 'Repeating Payment'), ('HOLD', 'Hold'), ('OTHER', 'Other')], max_length=25)),
                ('name', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='bank_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Account'),
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together=set([('account', 'transaction_id')]),
        ),
    ]
