# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20170312_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='kind',
            field=models.CharField(choices=[('BANK', 'Bank Account'), ('CREDITCARD', 'Credit Card')], default='BANK', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_posted',
            field=models.DateField(),
        ),
    ]
