# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20170312_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='starting_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
