# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 21:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0005_account_starting_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='finance.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='finance.Profile'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set([('profile', 'bank_id', 'account_id')]),
        ),
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
    ]
